### ISSUE TITLE
Introduce wrap for long lines

### ISSUE THREAD

**Issue by nestoru** [daviddengcn/patch-ext#6]
Thanks for this very helpful tool. Could you please introduce wrapping as an option? There are cases in which a long line that has changed causes the tool to be ineffective. I believe each vertical pane should always occupy just 50% of the real estate. 

Here is an example: https://raw.githubusercontent.com/nestoru/sharedissues/master/longline.patch

Makes sense?

**Comment by nestoru** [comment]
I have fixed this in my fork and made a pull request https://github.com/daviddengcn/patch-ext/pull/7

**Comment by daviddengcn** [comment]
Thanks for using the extension and warm-heartedly finding the problems and providing the solution. I gave the explanation of why relative distribution was not used. We can discuss the problem there.

Thanks again!
